### PR TITLE
[KIALI-1956] Fixing Kiali Complex Mesh Checker and Renaming old Meshes to Kiali Scale Mesh

### PR DESCRIPTION
**Pull request by gbaufake**

### CODE REVIEW

**Comment by jmazzitelli** [comment]
I installed the complex test mesh and this scale mesh:

```
NUM_SERVICES=4 NUM_VERSIONS=2 NUM_APPS=1 make openshift-deploy-kiali-test-depth
```

Looks like it installed OK.

I'm getting red edges, not sure if it is because of something on my local box or if its really broken:

image

I'll let this run for a while and see if it is cleans up.

**Comment by jmazzitelli** [comment]
I'm still seeing this - I think something is wrong with the test mesh stuff.

**Comment by gbaufake** [comment]
image

**Comment by gbaufake** [comment]
@jmazzitelli  are you getting this on your environment?

> cat results.bin | vegeta report
Requests      [total, rate]            134, 1.01
Duration      [total, attack, wait]    2m13.015407916s, 2m13.000003474s, 15.404442ms
Latencies     [mean, 50, 95, 99, max]  17.836791ms, 14.295933ms, 33.51792ms, 130.388486ms, 164.364006ms
Bytes In      [total, mean]            650, 4.85
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  97.01%
Status Codes  [code:count]             0:4  200:130
Error Set:
Get http://service-1.kiali-test-depth-0.svc.cluster.local/route?path=service-1.kiali-test-depth-0.svc.cluster.local,service-2.kiali-test-depth-0.svc.cluster.local,service-3.kiali-test-depth-0.svc.cluster.local,service-4.kiali-test-depth-0.svc.cluster.local: dial tcp 0.0.0.0:0->172.30.131.166:80: connect: connection refused

**Comment by jmazzitelli** [comment]
```
# cat results.bin | vegeta report
Requests      [total, rate]            12557, 1.00
Duration      [total, attack, wait]    3h29m16.009822148s, 3h29m16.000127814s, 9.694334ms
Latencies     [mean, 50, 95, 99, max]  9.967423ms, 3.843392ms, 23.889112ms, 118.809097ms, 2.236765988s
Bytes In      [total, mean]            710955, 56.62
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  37.49%
Status Codes  [code:count]             0:2  200:4708  503:7847
Error Set:
Get http://service-1.kiali-test-depth-0.svc.cluster.local/route?path=service-1.kiali-test-depth-0.svc.cluster.local,service-2.kiali-test-depth-0.svc.cluster.local,service-3.kiali-test-depth-0.svc.cluster.local,service-4.kiali-test-depth-0.svc.cluster.local: dial tcp 0.0.0.0:0->172.30.85.135:80: connect: connection refused
503 Service Unavailable
```

**Comment by jmazzitelli** [comment]
I shutdown and started a clean cluster - all I have is the test mesh. Still a bunch of red.

```
# cat results.bin | vegeta report
Requests      [total, rate]            341, 1.00
Duration      [total, attack, wait]    5m40.003394064s, 5m40.000083208s, 3.310856ms
Latencies     [mean, 50, 95, 99, max]  25.053482ms, 4.538016ms, 64.552224ms, 250.385979ms, 2.420889743s
Bytes In      [total, mean]            18595, 54.53
Bytes Out     [total, mean]            0, 0.00
Success       [ratio]                  49.56%
Status Codes  [code:count]             0:2  200:169  503:170
Error Set:
Get http://service-1.kiali-test-depth-0.svc.cluster.local/route?path=service-1.kiali-test-depth-0.svc.cluster.local,service-2.kiali-test-depth-0.svc.cluster.local,service-3.kiali-test-depth-0.svc.cluster.local,service-4.kiali-test-depth-0.svc.cluster.local: dial tcp 0.0.0.0:0->172.30.15.141:80: connect: connection refused
503 Service Unavailable
```

**Comment by jmazzitelli** [comment]
I re-installed with

**NUM_SERVICES=2** NUM_VERSIONS=2 NUM_APPS=1 make openshift-deploy-kiali-test-depth

and its all green.

**Comment by gbaufake** [comment]
It depends on the cluster. It seems 1 request per second it is too much to being handled on your environment with service.

**Pull request merged**
