### PR TITLE
Updating Scale Mesh to new Service Mesh 

### PR DESCRIPTION
**Pull request by gbaufake**
- Adding `ServiceMeshMember` to the namespaces
- Editing the CR for more straightforward configuration 
- Adding Finalizer for Removal via Openshift UI  
        - Manifests compliance ("coming next PR")

All the changes are available on `quay.io/kiali/kiali-test-mesh-operator:testing` and the CR of scale mesh is updated. A `make deploy-scale-mesh` should be enough after deploying the scale-mesh.

### CODE REVIEW

**Comment by gbaufake** [comment]
SCALE_MESH_NUMBER_SERVICES ?=10
SCALE_MESH_NUMBER_APPS ?=10
SCALE_MESH_NUMBER_VERSIONS ?=2
SCALE_MESH_NUMBER_NAMESPACES ?=1
SCALE_MESH_TYPE ?=  mesh-circle-callback

Captura de Tela 2020-04-16 às 19 40 27

**Comment by jshaughn** [comment]
@gbaufake Looks good.  Tell me, on auto-refresh do you ever see the large mesh resize in an odd way, like too small or too large, possible partially off-screen?

**Comment by gbaufake** [comment]
@jshaughn 
I have not seen it.
I have a big screen monitor (34') so I don't know if that would be a problem on smaller screens with bigger meshes (1000 apps on a small screen for example).

**Comment by pbajjuri20** [comment]
I have deployed and tested this PR, It successfully installed the Mesh.


mesh

**Pull request merged**
