### PR TITLE
Include Kiali test hourglass on Multiple Namespace Playbook

### PR DESCRIPTION
**Pull request by gbaufake**
Include Kiali Hourglass on Multiple Namespace

### CODE REVIEW

**Comment by gbaufake** [comment]
@jmazzitelli I think it is fixed on b30244c

**Comment by gbaufake** [comment]
screenshot_20180706_151835

**Comment by jmazzitelli** [comment]
This looks odd - why are my 2 commits from yesterday in this PR?  Do you need to rebase?

**Comment by gbaufake** [comment]
Fixed. Needed to rebase it

**Pull request merged**
