### PR TITLE
[KIALI-1622] Include Support on ComplexMesh

### PR DESCRIPTION
**Pull request by gbaufake**
Include Support on ComplexMesh for

- Deployment without Sidecar 
- ReplicaSet without Sidecar
- Statefulset
- Daemon Set

Best Regards,
Guilherme Baufaker Rêgo

### CODE REVIEW

**Comment by gbaufake** [comment]
@mwringe 
My Bad.

I forgot to add some files on the commit.

**Comment by lucasponce** [comment]
It could be good to support also:
- ReplicationControllers

Note, that Kiali supports Job/CronJobs, but those are not fully supported on Istio, so no need to use them to test.
(Basically, there is still an open issue in Istio as Jobs can't stop properly the sidecar).

**Comment by lucasponce** [comment]
> Weird Part, it is not present on Kiali Graph.

Is this confirmed ? We tested this feature with several scenarios and ReplicationControllers should appear with no issues cc @hhovsepy

**Comment by gbaufake** [comment]
@lucasponce @hhovsepy 
Opened [KIALI-1770](https://issues.jboss.org/projects/KIALI/issues/KIALI-1770) to discuss there 
. It seems to be something related to the graph itself not workloads page.

**Comment by lucasponce** [comment]
KIALI-1770 is a different JIRA, is ReplicationController only failing in the graph ?
Other workloads created from StatefulSet are visible in the Graph ?
Today I'm not available but I will take a look on monday morning.
Please, also check this QE JIRA https://issues.jboss.org/browse/KIALI-1521 and try also to check differences between the test data used and the mesh example.
Perhaps we can spot the differences and progress about it.

**Comment by lucasponce** [comment]
Another check: are pods created from de RC ?

**Pull request merged**
